const ActionTypes = {
  REQ_GET_LOGIN: 'REQ_GET_LOGIN',
  GET_LOGIN_RESPONSE : 'GET_LOGIN_RESPONSE',

  REQ_PAGINATE_USER: 'REQ_PAGINATE_USER',
  GET_PAGINATE_USER_RESPONSE: 'GET_PAGINATE_USER_RESPONSE',

  REQ_GET_USERS: 'REQ_GET_USERS',
  GET_USERS_RESPONSE: 'GET_USERS_RESPONSE',
  ADD_USER: 'ADD_USER',
  ADD_USER_RESPONSE: 'ADD_USER_RESPONSE',
  UPDATE_USER: 'UPDATE_USER',
  UPDATE_USER_RESPONSE: 'UPDATE_USER_RESPONSE',
  DEL_USER: 'DEL_USER',
  DEL_USER_RESPONSE: 'DEL_USER_RESPONSE',

  REQ_GET_PRODUCT: 'REQ_GET_PRODUCT',
  GET_PRODUCT_RESPONSE: 'GET_PRODUCT_RESPONSE',
  ADD_PRODUCT: 'ADD_PRODUCT',
  ADD_PRODUCT_RESPONSE: 'ADD_PRODUCT_RESPONSE',
  UPDATE_PRODUCT : 'UPDATE_PRODUCT',
  UPDATE_PRODUCT_RESPONSE : 'UPDATE_PRODUCT_RESPONSE',
  DEL_PRODUCT : 'DEL_PRODUCT',
  DEL_PRODUCT_RESPONSE : 'DEL_PRODUCT_RESPONSE',

  REQ_GET_CATEGORY: 'REQ_GET_CATEGORY',
  GET_CATEGORY_RESPONSE: 'GET_CATEGORY_RESPONSE',
  ADD_CATEGORY: 'ADD_CATEGORY',
  ADD_CATEGORY_RESPONSE: 'ADD_CATEGORY_RESPONSE',
  UPDATE_CATEGORY: 'UPDATE_CATEGORY',
  UPDATE_CATEGORY_RESPONSE: 'UPDATE_CATEGORY_RESPONSE',
  DEL_CATEGORY: 'DEL_CATEGORY',
  DEL_CATEGORY_RESPONSE: 'DEL_CATEGORY_RESPONSE'
};

export default ActionTypes;